planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  joint_state_topic: "/joint_states"
  attached_collision_object_topic: "/moveit_cpp/planning_scene_monitor"
  publish_planning_scene_topic: "/moveit_cpp/publish_planning_scene"
  monitored_planning_scene_topic: "/moveit_cpp/monitored_planning_scene"
  wait_for_initial_state_timeout: 10.0

planning_pipelines:
  #namespace: "moveit_cpp"  # optional, default is ~
  pipeline_names: ["pilz_industrial_motion_planner"]

plan_request_params:
  planning_attempts: 1
  planning_pipeline: pilz_industrial_motion_planner
  planner_id: "LIN"
  max_velocity_scaling_factor: 0.5
  max_acceleration_scaling_factor: 0.5