<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="robotcell_length" value="1" />
    <xacro:property name="robotcell_width" value="0.5" />
    <xacro:property name="robotcell_height" value="1" />

    <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />
    <xacro:arg name="use_nominal_extrinsics" default="false"/>
    <xacro:arg name="add_plug" default="false" />
    <xacro:arg name="use_mesh" default="true" />
    <xacro:sensor_d435 
        parent="robotcell_link" 
        use_nominal_extrinsics="$(arg use_nominal_extrinsics)" 
        add_plug="$(arg add_plug)" 
        use_mesh="$(arg use_mesh)">
        <origin xyz="-${robotcell_length/2} -${robotcell_width} -${robotcell_height}" rpy="0 -${pi/2} 0" />
    </xacro:sensor_d435>

</robot>