<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:property name="robot_center_offset_length" value="0.42" />
    <xacro:property name="robot_center_offset_width" value="0.02" />
    <xacro:property name="robot_base_height" value="0.99" />
    <xacro:property name="robotcell_length" value="1.44" />
    <xacro:property name="robotcell_width" value="0.94" />
    <xacro:property name="robotcell_height" value="1.16" />
    <xacro:property name="shield_thickness" value="0.03" />

    <material name="gray">
        <color rgba="0.6 0.8 0.8 1" />
    </material>

    <link name="shield_front_link">
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <box size="${robotcell_length} ${shield_thickness} ${robotcell_height}" />
            </geometry>
            <material name="gray"/>
        </collision>
        <xacro:inertial_box mass="5" x="${robotcell_length}" y="${shield_thickness}" z="${robotcell_height}">
            <origin rpy="0 0 0" xyz="0 0 0" />
        </xacro:inertial_box>
    </link>

    <link name="shield_rear_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <box size="${robotcell_length} ${shield_thickness} ${robotcell_height}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin rpy="0 0 0 " xyz="0 0 0" />
            <geometry>
                <box size="${robotcell_length} ${shield_thickness} ${robotcell_height}" />
            </geometry>
            <material name="gray"/>
        </collision>
        <xacro:inertial_box mass="5" x="${robotcell_length}" y="${shield_thickness}" z="${robotcell_height}">
            <origin rpy="0 0 0" xyz="0 0 0" />
        </xacro:inertial_box>
    </link>

    <link name="shield_right_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <box size="${shield_thickness} ${robotcell_width} ${robotcell_height}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <box size="${shield_thickness} ${robotcell_width} ${robotcell_height}" />
            </geometry>
            <material name="gray"/>
        </collision>
        <xacro:inertial_box mass="5" x="${shield_thickness}" y="${robotcell_width}" z="${robotcell_height}">
            <origin rpy="0 0 0" xyz="0 0 0" />
        </xacro:inertial_box>
    </link>

    <link name="shield_left_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <box size="${shield_thickness} ${robotcell_width} ${robotcell_height}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <box size="${shield_thickness} ${robotcell_width} ${robotcell_height}" />
            </geometry>
            <material name="gray"/>
        </collision>
        <xacro:inertial_box mass="5" x="${shield_thickness}" y="${robotcell_width}" z="${robotcell_height}">
            <origin rpy="0 0 0" xyz="0 0 0" />
        </xacro:inertial_box>
    </link>

    <link name="robotcell_base_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 ${robot_base_height/2}" />
            <geometry>
                <box size="${robotcell_length} ${robotcell_width} ${robot_base_height}" />
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 ${robot_base_height/2}" />
            <geometry>
                <box size="${robotcell_length} ${robotcell_width} ${robot_base_height}" />
            </geometry>
            <material name="gray"/>
        </collision>
        <xacro:inertial_box mass="70" x="${robotcell_length}" y="${robotcell_width}" z="${robot_base_height}">
            <origin rpy="0 0 0" xyz="0 0 0" />
        </xacro:inertial_box>
    </link>


    <joint name="robotcell_base_to_front_joint" type="fixed">
        <parent link="robotcell_base_link" />
        <child link="shield_front_link" />
        <origin xyz="0 ${robotcell_width/2-shield_thickness/2} ${robot_base_height+robotcell_height/2}" rpy="0 0 0" />
    </joint>

    <joint name="robotcell_base_to_rear" type="fixed">
        <parent link="robotcell_base_link" />
        <child link="shield_rear_link" />
        <origin xyz="0 ${-robotcell_width/2+shield_thickness/2} ${robot_base_height+robotcell_height/2}" rpy="0 0 0" />
    </joint>

    <joint name="robotcell_base_to_left" type="fixed">
        <parent link="robotcell_base_link" />
        <child link="shield_left_link" />
        <origin xyz="${-robotcell_length/2+shield_thickness/2} 0 ${robot_base_height+robotcell_height/2}" rpy="0 0 0" />
    </joint>

    <joint name="robotcell_jbase_to_right" type="fixed">
        <parent link="robotcell_base_link" />
        <child link="shield_right_link" />
        <origin xyz="${robotcell_length/2-shield_thickness/2} 0 ${robot_base_height+robotcell_height/2}" rpy="0 0 0" />
    </joint>


</robot>