# Default initial positions for ur5e_workcell's ros2_control fake system

initial_positions:
  elbow_joint: -1.57
  shoulder_lift_joint: -1.57
  shoulder_pan_joint: -1.57
  wrist_1_joint: -1.57
  wrist_2_joint: 1.57
  wrist_3_joint: 0.0

elbow_joint: -1.57
shoulder_lift_joint: -1.57
shoulder_pan_joint: -1.57
wrist_1_joint: -1.57
wrist_2_joint: 1.57
wrist_3_joint: 0.0